# Generated by Django 3.1.3 on 2021-05-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='utm_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='utm_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='yer',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Araliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.IntegerField(null=True)),
                ('su_turu', models.CharField(max_length=50, null=True)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('tekDeger', models.BooleanField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.location')),
                ('reading_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.readingtype')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='araliklar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.araliklar'),
        ),
    ]
