possible_row_names_2020 = [
    'NUMUNE KODU:',
    'BÖLGE ADI:',
    'YER:',
    'GPS KOORDİNATLARI:',
    'TABLO:',
    'NUMUNE ALMA TARİHİ',
    'PARAMETRE', # This is kind of useless since we have 'NUMUNE ALMA TARİHİ' anyway.
    'Amonyak (mg/ L)',
    'Amonyum Azotu (mg/ L)',
    'Askıda Katı Madde (mg/ L)',
    'Biyokimyasal Oksijen İhtiyacı (mg/ L)',
    'Debi (m3/ sn)',
    'Elektriksel İletkenlik (µS/ cm)',
    'Fekal  Koliform  (CFU/ 100 mL)',
    'Fekal Koliform (CFU/ 100 mL)',
    'Fekal Streptekok (CFU/ 100 mL)',
    'Işık Geçirgenliği (M)',
    'Kimyasal Oksijen İhtiyacı (mg/ L)',
    'Klorofil-A (µg/ L)',
    'Koku (TON)',
    'Nitrat Azotu (mg/ L)',
    'Nitrit Azotu (mg/ L)',
    'O2 (%)',
    'Orta Fosfat (mg/ L)',
    'Renk (Pt-Co)',
    'Sıcaklık (0C)',
    'Toplam Azot (mg/ L)',
    'Toplam Fenol (mg/ L)',
    'Toplam Fosfor (mg/ L)',
    'Toplam Kjeldahl Azotu (mg/ L)',
    'Toplam Koliform  (CFU/ 100 mL)',
    'Toplam Pestisid (mg/ L)',
    'Tuzluluk (‰)',
    'Yağ-Gres (mg/ L)',
    'pH',
    'Çözünmüş Oksijen (mg/ L)',
    'İletkenlik (µS/ cm)'
]

rows_with_data_2020 = [
    'NUMUNE ALMA TARİHİ',
    # 'PARAMETRE', # Meh.
    'Amonyak (mg/ L)',
    'Amonyum Azotu (mg/ L)',
    'Askıda Katı Madde (mg/ L)',
    'Biyokimyasal Oksijen İhtiyacı (mg/ L)',
    'Debi (m3/ sn)',
    'Elektriksel İletkenlik (µS/ cm)',
    'Fekal  Koliform  (CFU/ 100 mL)',
    'Fekal Koliform (CFU/ 100 mL)',
    'Fekal Streptekok (CFU/ 100 mL)',
    'Işık Geçirgenliği (M)',
    'Kimyasal Oksijen İhtiyacı (mg/ L)',
    'Klorofil-A (µg/ L)',
    'Koku (TON)',
    'Nitrat Azotu (mg/ L)',
    'Nitrit Azotu (mg/ L)',
    'O2 (%)',
    'Orta Fosfat (mg/ L)',
    'Renk (Pt-Co)',
    'Sıcaklık (0C)',
    'Toplam Azot (mg/ L)',
    'Toplam Fenol (mg/ L)',
    'Toplam Fosfor (mg/ L)',
    'Toplam Kjeldahl Azotu (mg/ L)',
    'Toplam Koliform  (CFU/ 100 mL)',
    'Toplam Pestisid (mg/ L)',
    'Tuzluluk (‰)',
    'Yağ-Gres (mg/ L)',
    'pH',
    'Çözünmüş Oksijen (mg/ L)',
    'İletkenlik (µS/ cm):'
]