possible_row_names_2020 = [
    'NUMUNE KODU:',
    'BÖLGE ADI:',
    'YER:',
    'GPS KOORDİNATLARI:',
    'TABLO:',
    'NUMUNE ALMA TARİHİ',
    'PARAMETRE', # This is kind of useless since we have 'NUMUNE ALMA TARİHİ' anyway.
    'Amonyak (mg/ L)',
    'Amonyum Azotu (mg/ L)',
    'Askıda Katı Madde (mg/ L)',
    'Biyokimyasal Oksijen İhtiyacı (mg/ L)',
    'Debi (m3/ sn)',
    'Elektriksel İletkenlik (µS/ cm)',
    'Fekal  Koliform  (CFU/ 100 mL)',
    'Fekal Koliform (CFU/ 100 mL)',
    'Fekal Streptekok (CFU/ 100 mL)',
    'Işık Geçirgenliği (M)',
    'Kimyasal Oksijen İhtiyacı (mg/ L)',
    'Klorofil-A (µg/ L)',
    'Koku (TON)',
    'Nitrat Azotu (mg/ L)',
    'Nitrit Azotu (mg/ L)',
    'O2 (%)',
    'Orta Fosfat (mg/ L)',
    'Renk (Pt-Co)',
    'Sıcaklık (0C)',
    'Toplam Azot (mg/ L)',
    'Toplam Fenol (mg/ L)',
    'Toplam Fosfor (mg/ L)',
    'Toplam Kjeldahl Azotu (mg/ L)',
    'Toplam Koliform  (CFU/ 100 mL)',
    'Toplam Pestisid (mg/ L)',
    'Tuzluluk (‰)',
    'Yağ-Gres (mg/ L)',
    'pH',
    'Çözünmüş Oksijen (mg/ L)',
    'İletkenlik (µS/ cm)'
]

rows_with_data_2020 = [
    'NUMUNE ALMA TARİHİ',
    # 'PARAMETRE', # Meh.
    'Amonyak (mg/ L)',
    'Amonyum Azotu (mg/ L)',
    'Askıda Katı Madde (mg/ L)',
    'Biyokimyasal Oksijen İhtiyacı (mg/ L)',
    'Debi (m3/ sn)',
    'Elektriksel İletkenlik (µS/ cm)',
    'Fekal  Koliform  (CFU/ 100 mL)',
    'Fekal Koliform (CFU/ 100 mL)',
    'Fekal Streptekok (CFU/ 100 mL)',
    'Işık Geçirgenliği (M)',
    'Kimyasal Oksijen İhtiyacı (mg/ L)',
    'Klorofil-A (µg/ L)',
    'Koku (TON)',
    'Nitrat Azotu (mg/ L)',
    'Nitrit Azotu (mg/ L)',
    'O2 (%)',
    'Orta Fosfat (mg/ L)',
    'Renk (Pt-Co)',
    'Sıcaklık (0C)',
    'Toplam Azot (mg/ L)',
    'Toplam Fenol (mg/ L)',
    'Toplam Fosfor (mg/ L)',
    'Toplam Kjeldahl Azotu (mg/ L)',
    'Toplam Koliform  (CFU/ 100 mL)',
    'Toplam Pestisid (mg/ L)',
    'Tuzluluk (‰)',
    'Yağ-Gres (mg/ L)',
    'pH',
    'Çözünmüş Oksijen (mg/ L)',
    'İletkenlik (µS/ cm):'
]

possible_row_names_2018 = [
    'Toplam Fosfor (μg/L)', 
    'Nitrit Azotu (mg/L)', 
    'Toplam Koliform (CFU/100mL)', 
    'pH', 
    'Yer', 
    'Toplam Azot (mg/L)', 
    'Kimyasal Oksijen İhtiyacı (mg/L)', 
    'Toplam Koliform (CFU/ 100mL)', 
    'Amonyum Azotu (mg/L)', 
    'Debi (m3/sn)', 
    'Fekal Koliform (CFU/100mL)', 
    'Çözünmüş Oksijen (mg/L)', 
    'Renk (Pt-Co)', 
    'GPS Koordinatları', 
    'Parametre', 
    'Sıcaklık (oC)', 
    'TVKGM Numune Kodu', 
    'No', 
    'Klorofil-a (μg/L)', 
    'Toplam Pestisit (mg/L)', 
    'O2 (%)', 
    'Toplam Koliform \n(CFU/ 100mL)', 
    'ÖÇKB Adı', 
    'Fekal Koliform \n(CFU/ 100mL)', 
    'Nitrat Azotu (mg/L)', 
    'Toplam Azot (μg/L)', 
    'Yağ-Gres (mg/L)', 
    'Sıcaklık(0C)', 
    'Fekal Koliform (CFU/ 100mL)', 
    'Toplam Fosfor (mg/L)', 
    'Numune Alma Tarihi', 
    'Debi (m3/gün)', 
    'Amonyak (mg/L)', 
    'Askıda Katı Madde (mg/L)', 
    'Toplam Fenol (mg/L)', 
    'Işık Geçirgenliği (m)', 
    'DOKAY Numune Kayıt Numarası', 
    'İletkenlik (μs/cm)', 
    'Biyokimyasal Oksijen İhtiyacı (mg/L)', 
    'Sıcaklık (0C)', 
    'Tuzluluk (‰)', 
    'Toplam Kjeldahl Azotu (mg/L)', 
    'Elektriksel İletkenlik (μs/cm)', 
    'FekalStreptekok \n(CFU/ 100mL)', 
    'FekalStreptekok (CFU/ 100mL)', 
    'Koku (TON)'
]